name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "paste.yizhan.wiki"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "5750a219f57a4f2b95ea8dae050c1d42"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://paste.yizhan.wiki"

# url to repo, displayed in index page
REPO = "https://github.com/lilingfengdev/NitWikit-Pastebin"

# url to favicon
FAVICON = "https://yizhan.wiki/NitWikit/img/book.png"

# the name displayed in TOS
TOS_MAINTAINER = "笨蛋粘贴板"

# the email displayed in TOS
TOS_MAIL = "pb@shz.al"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
